### ISSUE TITLE
ニコレポの仕様変更による不具合

### ISSUE THREAD

**Issue by foooomio** [fushihara/nico-repo#3]
最近のニコ動側の仕様変更で、NicorepoTimeLineItemにニコレポのタイプ別のclass名がつかなくなってしまって、動作していないようです。こちら対応可能でしょうか？

![2017-06-05 16 51 23](https://cloud.githubusercontent.com/assets/1075914/26775514/46a8f14a-4a10-11e7-99cf-024c5df82ae9.png)

もしよろしければ、修正や動作確認等、お手伝い可能です。
（私もこの仕様変更には困っている身ですので…）

**Comment by tikusieg** [comment]
力添えはできなくて恐縮ですが、今後はdiv.NicorepoTimelineItem > div.log-content > div.log-body > spanのテキストで判別するしかなさそうですね。

**Comment by fushihara** [comment]
ありがとうございます。クラス名が出ないのは困りますね。
ご指摘の通り、テキストを正規化して比較するように致しました。

構造は簡単なjsonをajaxで引っ張っているだけなので、もう完全に自力の実装に置き換えてもいいのかも
